### PR TITLE
Change the discovery url to point to production env

### PR DESCRIPTION
**Pull request by mandaryadav**
Change the default discovery url to point to the production environment.

### CODE REVIEW

**Comment by tylerbutler** [comment]
@mandaryadav It seems to me that the test environment is the correct default. The majority of cases where the tool will be used will be as part of testing prior to going to production. Why change the default? Also the test environment will always have the latest validator tests, while production will lag behind.

**Comment by mandaryadav** [comment]
@tylerbutler I observed that one of the 3rd party host (Edmodo) was running the validation application from the production environment so to keep it consistent, I proposed this change to make it as a default. If that is not necessary then feel free to discard my change.

**Comment by tylerbutler** [comment]
@mandaryadav Yeah, I think the test environment is the right default. Most partners won't even have access to prod when using this initially, so they'd just get errors by default. I'll go ahead and close this PR.

**Comment by mandaryadav** [comment]
Thanks @tylerbutler

**Pull request closed without merging**
